// Generated by scripts/sync-fonts.mjs. Do not edit by hand.
export interface FontEntry {
  id: string;
  name: string;
  group: string;
  /** weight to file URL. 400 always exists. 700 only if the family has a bold. */
  files: Record<number, string>;
}

export const FONTS: FontEntry[] = [
  {
    "id": "inter",
    "name": "Inter",
    "group": "Sans",
    "files": {
      "400": "/fonts/inter-latin-400-normal.woff2",
      "700": "/fonts/inter-latin-700-normal.woff2"
    }
  },
  {
    "id": "montserrat",
    "name": "Montserrat",
    "group": "Sans",
    "files": {
      "400": "/fonts/montserrat-latin-400-normal.woff2",
      "700": "/fonts/montserrat-latin-700-normal.woff2"
    }
  },
  {
    "id": "poppins",
    "name": "Poppins",
    "group": "Sans",
    "files": {
      "400": "/fonts/poppins-latin-400-normal.woff2",
      "700": "/fonts/poppins-latin-700-normal.woff2"
    }
  },
  {
    "id": "raleway",
    "name": "Raleway",
    "group": "Sans",
    "files": {
      "400": "/fonts/raleway-latin-400-normal.woff2",
      "700": "/fonts/raleway-latin-700-normal.woff2"
    }
  },
  {
    "id": "dm-sans",
    "name": "DM Sans",
    "group": "Sans",
    "files": {
      "400": "/fonts/dm-sans-latin-400-normal.woff2",
      "700": "/fonts/dm-sans-latin-700-normal.woff2"
    }
  },
  {
    "id": "work-sans",
    "name": "Work Sans",
    "group": "Sans",
    "files": {
      "400": "/fonts/work-sans-latin-400-normal.woff2",
      "700": "/fonts/work-sans-latin-700-normal.woff2"
    }
  },
  {
    "id": "manrope",
    "name": "Manrope",
    "group": "Sans",
    "files": {
      "400": "/fonts/manrope-latin-400-normal.woff2",
      "700": "/fonts/manrope-latin-700-normal.woff2"
    }
  },
  {
    "id": "outfit",
    "name": "Outfit",
    "group": "Sans",
    "files": {
      "400": "/fonts/outfit-latin-400-normal.woff2",
      "700": "/fonts/outfit-latin-700-normal.woff2"
    }
  },
  {
    "id": "space-grotesk",
    "name": "Space Grotesk",
    "group": "Sans",
    "files": {
      "400": "/fonts/space-grotesk-latin-400-normal.woff2",
      "700": "/fonts/space-grotesk-latin-700-normal.woff2"
    }
  },
  {
    "id": "syne",
    "name": "Syne",
    "group": "Sans",
    "files": {
      "400": "/fonts/syne-latin-400-normal.woff2",
      "700": "/fonts/syne-latin-700-normal.woff2"
    }
  },
  {
    "id": "bricolage-grotesque",
    "name": "Bricolage Grotesque",
    "group": "Sans",
    "files": {
      "400": "/fonts/bricolage-grotesque-latin-400-normal.woff2",
      "700": "/fonts/bricolage-grotesque-latin-700-normal.woff2"
    }
  },
  {
    "id": "josefin-sans",
    "name": "Josefin Sans",
    "group": "Sans",
    "files": {
      "400": "/fonts/josefin-sans-latin-400-normal.woff2",
      "700": "/fonts/josefin-sans-latin-700-normal.woff2"
    }
  },
  {
    "id": "rubik",
    "name": "Rubik",
    "group": "Sans",
    "files": {
      "400": "/fonts/rubik-latin-400-normal.woff2",
      "700": "/fonts/rubik-latin-700-normal.woff2"
    }
  },
  {
    "id": "archivo-black",
    "name": "Archivo Black",
    "group": "Display",
    "files": {
      "400": "/fonts/archivo-black-latin-400-normal.woff2"
    }
  },
  {
    "id": "oswald",
    "name": "Oswald",
    "group": "Display",
    "files": {
      "400": "/fonts/oswald-latin-400-normal.woff2",
      "700": "/fonts/oswald-latin-700-normal.woff2"
    }
  },
  {
    "id": "anton",
    "name": "Anton",
    "group": "Display",
    "files": {
      "400": "/fonts/anton-latin-400-normal.woff2"
    }
  },
  {
    "id": "bebas-neue",
    "name": "Bebas Neue",
    "group": "Display",
    "files": {
      "400": "/fonts/bebas-neue-latin-400-normal.woff2"
    }
  },
  {
    "id": "abril-fatface",
    "name": "Abril Fatface",
    "group": "Display",
    "files": {
      "400": "/fonts/abril-fatface-latin-400-normal.woff2"
    }
  },
  {
    "id": "dm-serif-display",
    "name": "DM Serif Display",
    "group": "Display",
    "files": {
      "400": "/fonts/dm-serif-display-latin-400-normal.woff2"
    }
  },
  {
    "id": "playfair-display",
    "name": "Playfair Display",
    "group": "Serif",
    "files": {
      "400": "/fonts/playfair-display-latin-400-normal.woff2",
      "700": "/fonts/playfair-display-latin-700-normal.woff2"
    }
  },
  {
    "id": "lora",
    "name": "Lora",
    "group": "Serif",
    "files": {
      "400": "/fonts/lora-latin-400-normal.woff2",
      "700": "/fonts/lora-latin-700-normal.woff2"
    }
  },
  {
    "id": "cormorant-garamond",
    "name": "Cormorant Garamond",
    "group": "Serif",
    "files": {
      "400": "/fonts/cormorant-garamond-latin-400-normal.woff2",
      "700": "/fonts/cormorant-garamond-latin-700-normal.woff2"
    }
  },
  {
    "id": "libre-baskerville",
    "name": "Libre Baskerville",
    "group": "Serif",
    "files": {
      "400": "/fonts/libre-baskerville-latin-400-normal.woff2",
      "700": "/fonts/libre-baskerville-latin-700-normal.woff2"
    }
  },
  {
    "id": "fraunces",
    "name": "Fraunces",
    "group": "Serif",
    "files": {
      "400": "/fonts/fraunces-latin-400-normal.woff2",
      "700": "/fonts/fraunces-latin-700-normal.woff2"
    }
  },
  {
    "id": "merriweather",
    "name": "Merriweather",
    "group": "Serif",
    "files": {
      "400": "/fonts/merriweather-latin-400-normal.woff2",
      "700": "/fonts/merriweather-latin-700-normal.woff2"
    }
  },
  {
    "id": "pacifico",
    "name": "Pacifico",
    "group": "Script and hand",
    "files": {
      "400": "/fonts/pacifico-latin-400-normal.woff2"
    }
  },
  {
    "id": "lobster",
    "name": "Lobster",
    "group": "Script and hand",
    "files": {
      "400": "/fonts/lobster-latin-400-normal.woff2"
    }
  },
  {
    "id": "dancing-script",
    "name": "Dancing Script",
    "group": "Script and hand",
    "files": {
      "400": "/fonts/dancing-script-latin-400-normal.woff2",
      "700": "/fonts/dancing-script-latin-700-normal.woff2"
    }
  },
  {
    "id": "caveat",
    "name": "Caveat",
    "group": "Script and hand",
    "files": {
      "400": "/fonts/caveat-latin-400-normal.woff2",
      "700": "/fonts/caveat-latin-700-normal.woff2"
    }
  },
  {
    "id": "permanent-marker",
    "name": "Permanent Marker",
    "group": "Script and hand",
    "files": {
      "400": "/fonts/permanent-marker-latin-400-normal.woff2"
    }
  }
];
