#!/usr/bin/env python3
"""Generate tokens.css and tailwind.theme.css from tokens.json. Standard library only.

    python3 design/build_tokens.py src/styles

Edit tokens.json, run this, then run
python3 contrast.py tokens.json. Components never contain raw hex, so a
rebrand is a values-only change.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# where the generated CSS goes: the first argument, or next to tokens.json
OUT = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else HERE

# role name in tokens.json -> Tailwind colour key (bg-page, text-ink, border-line ...)
TW_COLOR = {
    "bg": "page", "surface": "surface", "surface-hover": "surface-hover",
    "canvas": "canvas", "border": "line", "border-input": "field",
    "text": "ink", "text-muted": "muted", "accent": "accent",
    "accent-hover": "accent-hover", "accent-active": "accent-active",
    "accent-soft": "accent-soft", "on-accent": "on-accent", "danger": "danger",
    "danger-hover": "danger-hover", "success": "success", "warning": "warning",
    "guide": "guide", "overlay": "overlay",
}


def px(n):
    return "%dpx" % n


def main():
    with open(os.path.join(HERE, "tokens.json"), encoding="utf-8") as fh:
        t = json.load(fh)

    css = ["/* Generated by build_tokens.py from tokens.json. Do not edit by hand. */", ":root {"]
    for k, v in t["color"].items():
        css.append("  --%s: %s;" % (k, v))
    css.append("  --ff-sans: %s;" % t["font"]["sans"])
    css.append("  --ff-mono: %s;" % t["font"]["mono"])
    for k, v in t["type"].items():
        css.append("  --type-%s-size: %s;" % (k, px(v["size"])))
        css.append("  --type-%s-line: %s;" % (k, px(v["line"])))
        css.append("  --type-%s-weight: %d;" % (k, v["weight"]))
    for i, v in enumerate(t["space"]):
        css.append("  --space-%d: %s;" % (i, px(v)))
    for k, v in t["radius"].items():
        css.append("  --r-%s: %s;" % (k, px(v)))
    for k, v in t["shadow"].items():
        css.append("  --sh-%s: %s;" % (k, v))
    css.append("  --motion-fast: %s;" % t["motion"]["fast"])
    css.append("  --motion-base: %s;" % t["motion"]["base"])
    css.append("  --motion-ease: %s;" % t["motion"]["ease"])
    for k, v in t["layout"].items():
        css.append("  --layout-%s: %s;" % (k, px(v)))
    for k, v in t["z"].items():
        css.append("  --z-%s: %d;" % (k, v))
    css.append("}")
    css.append("")
    css.append("@media (prefers-reduced-motion: reduce) {")
    css.append("  :root { --motion-fast: 0ms; --motion-base: 0ms; }")
    css.append("}")
    css.append("")
    with open(os.path.join(OUT, "tokens.css"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(css))

    tw = [
        "/* Generated by build_tokens.py from tokens.json. Tailwind v4 theme. */",
        "/* Import after tokens.css:  @import \"./tokens.css\"; @import \"tailwindcss\"; @import \"./tailwind.theme.css\"; */",
        "@theme inline {",
        "  /* No raw palette. Components use roles only. */",
        "  --color-*: initial;",
    ]
    for role, key in TW_COLOR.items():
        if role in t["color"]:
            tw.append("  --color-%s: var(--%s);" % (key, role))
    tw.append("")
    tw.append("  --font-sans: var(--ff-sans);")
    tw.append("  --font-mono: var(--ff-mono);")
    tw.append("")
    for k in t["type"]:
        tw.append("  --text-%s: var(--type-%s-size);" % (k, k))
        tw.append("  --text-%s--line-height: var(--type-%s-line);" % (k, k))
    tw.append("")
    for k in t["radius"]:
        tw.append("  --radius-%s: var(--r-%s);" % (k, k))
    for k in t["shadow"]:
        tw.append("  --shadow-%s: var(--sh-%s);" % (k, k))
    tw.append("  --ease-app: var(--motion-ease);")
    tw.append("}")
    tw.append("")
    with open(os.path.join(OUT, "tailwind.theme.css"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(tw))
    print("wrote tokens.css and tailwind.theme.css")


if __name__ == "__main__":
    main()
