/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ShareComments {
  body: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  shareId: string;
  slide: number | null;
}

export interface ShareLimits {
  clientHash: string;
  day: Timestamp;
  made: Generated<number>;
}

export interface Shares {
  aspect: number;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ownerTokenHash: string;
  slideCount: number;
  status: Generated<string>;
  title: string;
}

export interface DB {
  shareComments: ShareComments;
  shareLimits: ShareLimits;
  shares: Shares;
}




// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.