// Copies the slide fonts out of the @fontsource packages into public/fonts, and writes the manifest the
// editor reads (src/lib/fonts.generated.ts) and a licence list. Run: npm run fonts
// Only the Latin subset, regular and bold. Each font file is fetched only when a project uses it.
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const FAMILIES = [
  ["Sans", ["inter", "Inter"], ["montserrat", "Montserrat"], ["poppins", "Poppins"], ["raleway", "Raleway"], ["dm-sans", "DM Sans"], ["work-sans", "Work Sans"], ["manrope", "Manrope"], ["outfit", "Outfit"], ["space-grotesk", "Space Grotesk"], ["syne", "Syne"], ["bricolage-grotesque", "Bricolage Grotesque"], ["josefin-sans", "Josefin Sans"], ["rubik", "Rubik"]],
  ["Display", ["archivo-black", "Archivo Black"], ["oswald", "Oswald"], ["anton", "Anton"], ["bebas-neue", "Bebas Neue"], ["abril-fatface", "Abril Fatface"], ["dm-serif-display", "DM Serif Display"]],
  ["Serif", ["playfair-display", "Playfair Display"], ["lora", "Lora"], ["cormorant-garamond", "Cormorant Garamond"], ["libre-baskerville", "Libre Baskerville"], ["fraunces", "Fraunces"], ["merriweather", "Merriweather"]],
  ["Script and hand", ["pacifico", "Pacifico"], ["lobster", "Lobster"], ["dancing-script", "Dancing Script"], ["caveat", "Caveat"], ["permanent-marker", "Permanent Marker"]],
];

const out = path.resolve("public/fonts");
fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });

const manifest = [];
const licences = [];
for (const [group, ...fams] of FAMILIES) {
  for (const [id, name] of fams) {
    const dir = path.dirname(require.resolve(`@fontsource/${id}/package.json`));
    const pkg = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
    const files = {};
    for (const w of [400, 700]) {
      const f = `${id}-latin-${w}-normal.woff2`;
      if (fs.existsSync(path.join(dir, "files", f))) {
        fs.copyFileSync(path.join(dir, "files", f), path.join(out, f));
        files[w] = `/fonts/${f}`;
      }
    }
    if (!files[400]) throw new Error(`${id} has no regular weight`);
    manifest.push({ id, name, group, files });
    licences.push(`| ${name} | ${pkg.license} | ${pkg.version} |`);
    const lic = path.join(dir, "LICENSE");
    if (fs.existsSync(lic)) fs.copyFileSync(lic, path.join(out, `LICENSE-${id}.txt`));
  }
}

fs.writeFileSync(
  "src/lib/fonts.generated.ts",
  `// Generated by scripts/sync-fonts.mjs. Do not edit by hand.\nexport interface FontEntry {\n  id: string;\n  name: string;\n  group: string;\n  /** weight to file URL. 400 always exists. 700 only if the family has a bold. */\n  files: Record<number, string>;\n}\n\nexport const FONTS: FontEntry[] = ${JSON.stringify(manifest, null, 2)};\n`,
);
fs.writeFileSync(
  path.join(out, "LICENSES.md"),
  `# Fonts used for slide text\n\nSelf-hosted from the Fontsource packages. Each family's licence file is next to this one (LICENSE-<family>.txt).\nThe fonts are free to use and redistribute under their licences. Keep these files when you deploy.\n\n| family | licence | package version |\n| --- | --- | --- |\n${licences.join("\n")}\n`,
);
console.log(`${manifest.length} families, ${fs.readdirSync(out).filter((f) => f.endsWith(".woff2")).length} files, ${(fs.readdirSync(out).reduce((n, f) => n + fs.statSync(path.join(out, f)).size, 0) / 1e6).toFixed(1)} MB`);
